name = "PubChem"
uuid = "1db272ca-bb6a-4d7c-9426-e93aef723262"
version = "1.2.0"
authors = ["Lalit Chauhan"]

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
ArrayInterface = "7"
Catalyst = "13, 14"
ExplicitImports = "1"
HTTP = "1.9.6"
JLArrays = "0.3"
JSON = "0.21.4"
ModelingToolkit = "9"
SymbolicUtils = "1.7.1, 2, 3"
Symbolics = "6"
julia = "1.10"

[extras]
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "ExplicitImports", "JLArrays"]
